#!/bin/bash

var_java=/usr/lib/jvm/java-8-openjdk-amd64

echo Editing bashrc file
echo "export HADOOP_HOME=/usr/hadoop" >> /home/$SUDO_USER/.bashrc
echo "export JAVA_HOME=$var_java" >> /home/$SUDO_USER/.bashrc
echo "export PATH=$PATH:$HADOOP_HOME/bin" >> /home/$SUDO_USER/.bashrc
